### ISSUE TITLE
How to configure to run in docker cloud environment?

### ISSUE THREAD

**Issue by metalaureate** [jacebrowning/memegen#213]
Any clues on running in docker?

My Dockerfile

```
ADD ./ /usr/local/src/meme-gen/
RUN apt-get -y update && apt-get -y install imagemagick

WORKDIR /usr/local/src/meme-gen/
RUN  python setup.py install
CMD gunicorn manage:app -b 0.0.0.0:8000 --config gunicorn.config.py
```

I had to change the port 0.0.0.0 to run in Docker Cloud. I also opened up port 5432. And made this request:
`/custom/my-pretty/background.jpg?alt=http://www.gstatic.com/webp/gallery/1.jpg`

 But that looks like it broke everything.

```
meme-gen-1 | 2016-05-30T20:14:23.392010174Z [2016-05-30 20:14:23 +0000] [1] [INFO] Starting gunicorn 19.3.0
meme-gen-1 | 2016-05-30T20:14:23.393427397Z [2016-05-30 20:14:23 +0000] [1] [INFO] Listening at: http://0.0.0.0:8000 (1)
meme-gen-1 | 2016-05-30T20:14:23.393634233Z [2016-05-30 20:14:23 +0000] [1] [INFO] Using worker: threads
meme-gen-1 | 2016-05-30T20:14:23.396313526Z [2016-05-30 20:14:23 +0000] [9] [INFO] Booting worker with pid: 9
meme-gen-1 | 2016-05-30T20:14:45.753025458Z INFO: Downloading http://www.gstatic.com/webp/gallery/1.jpg
meme-gen-1 | 2016-05-30T20:14:45.780812216Z [2016-05-30 20:14:45 +0000] [9] [ERROR] Error handling request
meme-gen-1 | 2016-05-30T20:14:45.780860443Z Traceback (most recent call last):
meme-gen-1 | 2016-05-30T20:14:45.780868915Z   File "/usr/local/lib/python3.5/site-packages/SQLAlchemy-1.0.12-py3.5-linux-x86_64.egg/sqlalchemy/pool.py", line 1044, in _do_get
meme-gen-1 | 2016-05-30T20:14:45.780877143Z     return self._pool.get(wait, self._timeout)
meme-gen-1 | 2016-05-30T20:14:45.780882632Z   File "/usr/local/lib/python3.5/site-packages/SQLAlchemy-1.0.12-py3.5-linux-x86_64.egg/sqlalchemy/util/queue.py", line 145, in get
meme-gen-1 | 2016-05-30T20:14:45.780888405Z     raise Empty
meme-gen-1 | 2016-05-30T20:14:45.780894041Z sqlalchemy.util.queue.Empty
meme-gen-1 | 2016-05-30T20:14:45.780899229Z 
meme-gen-1 | 2016-05-30T20:14:45.780904303Z During handling of the above exception, another exception occurred:
meme-gen-1 | 2016-05-30T20:14:45.780909689Z 
meme-gen-1 | 2016-05-30T20:14:45.780914562Z Traceback (most recent call last):
meme-gen-1 | 2016-05-30T20:14:45.780920054Z   File "/usr/local/lib/python3.5/site-packages/SQLAlchemy-1.0.12-py3.5-linux-x86_64.egg/sqlalchemy/engine/base.py", line 2074, in _wrap_pool_connect
meme-gen-1 | 2016-05-30T20:14:45.780925749Z     return fn()
meme-gen-1 | 2016-05-30T20:14:45.780930990Z   File "/usr/local/lib/python3.5/site-packages/SQLAlchemy-1.0.12-py3.5-linux-x86_64.egg/sqlalchemy/pool.py", line 376, in connect
meme-gen-1 | 2016-05-30T20:14:45.780936616Z     return _ConnectionFairy._checkout(self)
meme-gen-1 | 2016-05-30T20:14:45.780941790Z   File "/usr/local/lib/python3.5/site-packages/SQLAlchemy-1.0.12-py3.5-linux-x86_64.egg/sqlalchemy/pool.py", line 713, in _checkout
meme-gen-1 | 2016-05-30T20:14:45.780947321Z     fairy = _ConnectionRecord.checkout(pool)
meme-gen-1 | 2016-05-30T20:14:45.780952579Z   File "/usr/local/lib/python3.5/site-packages/SQLAlchemy-1.0.12-py3.5-linux-x86_64.egg/sqlalchemy/pool.py", line 480, in checkout
meme-gen-1 | 2016-05-30T20:14:45.780958156Z     rec = pool._do_get()
meme-gen-1 | 2016-05-30T20:14:45.780963423Z   File "/usr/local/lib/python3.5/site-packages/SQLAlchemy-1.0.12-py3.5-linux-x86_64.egg/sqlalchemy/pool.py", line 1060, in _do_get
meme-gen-1 | 2016-05-30T20:14:45.780968941Z     self._dec_overflow()
meme-gen-1 | 2016-05-30T20:14:45.780974046Z   File "/usr/local/lib/python3.5/site-packages/SQLAlchemy-1.0.12-py3.5-linux-x86_64.egg/sqlalchemy/util/langhelpers.py", line 60, in __exit__
meme-gen-1 | 2016-05-30T20:14:45.780979539Z     compat.reraise(exc_type, exc_value, exc_tb)
meme-gen-1 | 2016-05-30T20:14:45.780984653Z   File "/usr/local/lib/python3.5/site-packages/SQLAlchemy-1.0.12-py3.5-linux-x86_64.egg/sqlalchemy/util/compat.py", line 184, in reraise
meme-gen-1 | 2016-05-30T20:14:45.780990092Z     raise value
meme-gen-1 | 2016-05-30T20:14:45.781005200Z   File "/usr/local/lib/python3.5/site-packages/SQLAlchemy-1.0.12-py3.5-linux-x86_64.egg/sqlalchemy/pool.py", line 1057, in _do_get
meme-gen-1 | 2016-05-30T20:14:45.781011348Z     return self._create_connection()
meme-gen-1 | 2016-05-30T20:14:45.781016537Z   File "/usr/local/lib/python3.5/site-packages/SQLAlchemy-1.0.12-py3.5-linux-x86_64.egg/sqlalchemy/pool.py", line 323, in _create_connection
meme-gen-1 | 2016-05-30T20:14:45.781022169Z     return _ConnectionRecord(self)
meme-gen-1 | 2016-05-30T20:14:45.781027320Z   File "/usr/local/lib/python3.5/site-packages/SQLAlchemy-1.0.12-py3.5-linux-x86_64.egg/sqlalchemy/pool.py", line 449, in __init__
meme-gen-1 | 2016-05-30T20:14:45.781032848Z     self.connection = self.__connect()
meme-gen-1 | 2016-05-30T20:14:45.781038011Z   File "/usr/local/lib/python3.5/site-packages/SQLAlchemy-1.0.12-py3.5-linux-x86_64.egg/sqlalchemy/pool.py", line 607, in __connect
meme-gen-1 | 2016-05-30T20:14:45.781044521Z     connection = self.__pool._invoke_creator(self)
meme-gen-1 | 2016-05-30T20:14:45.781049630Z   File "/usr/local/lib/python3.5/site-packages/SQLAlchemy-1.0.12-py3.5-linux-x86_64.egg/sqlalchemy/engine/strategies.py", line 97, in connect
meme-gen-1 | 2016-05-30T20:14:45.781055130Z     return dialect.connect(*cargs, **cparams)
meme-gen-1 | 2016-05-30T20:14:45.781060259Z   File "/usr/local/lib/python3.5/site-packages/SQLAlchemy-1.0.12-py3.5-linux-x86_64.egg/sqlalchemy/engine/default.py", line 385, in connect
meme-gen-1 | 2016-05-30T20:14:45.781065745Z     return self.dbapi.connect(*cargs, **cparams)
meme-gen-1 | 2016-05-30T20:14:45.781070856Z   File "/usr/local/lib/python3.5/site-packages/psycopg2-2.6.1-py3.5-linux-x86_64.egg/psycopg2/__init__.py", line 164, in connect
meme-gen-1 | 2016-05-30T20:14:45.781076430Z     conn = _connect(dsn, connection_factory=connection_factory, async=async)
meme-gen-1 | 2016-05-30T20:14:45.781081596Z psycopg2.OperationalError: could not connect to server: Connection refused
meme-gen-1 | 2016-05-30T20:14:45.781086848Z   Is the server running on host "localhost" (::1) and accepting
meme-gen-1 | 2016-05-30T20:14:45.781092358Z   TCP/IP connections on port 5432?
meme-gen-1 | 2016-05-30T20:14:45.781097597Z could not connect to server: Connection refused
meme-gen-1 | 2016-05-30T20:14:45.781102726Z   Is the server running on host "localhost" (127.0.0.1) and accepting connections on port 5432
```

**Comment by metalaureate** [comment]
My problem seems to be that whatever is supposed to be running at 5432 is not running. I've logged into the container and verified that nothing is running on 5432.

**Comment by jacebrowning** [comment]
It uses PostgreSQL to store some metrics on images requests.

Ideally the PostgrSQL dependency would be optional. I'd be happy to review a PR that completely skips the database code if the `DATABASE_URL` environment variable is unset. This already happens for tests running on Appveyor.

Otherwise, I think you'll need PostgreSQL running on port 5432 (the default).

**Comment by metalaureate** [comment]
@jacebrowning Thanks for the clarification. Can you point me to the schema and username and password config so I can configure the db it expects? So far I added `apt-get install postgresql-9.4` to my Dockerfile but that does not yet the db running.

**Comment by jacebrowning** [comment]
I don't know how to configure PostgreSQL in your container, but you will need to create a database named `memegen_dev` and set `DATABASE_URL=postgresql://localhost/memegen_dev`.

**Comment by metalaureate** [comment]
@jacebrowning On second thoughts, I will follow the stack traces and try to remove it.

**Comment by metalaureate** [comment]
I decided it would be nice to have meme stats too, so I set up a remote postgres db.

For future users of your project, the schema is as follows:

```
CREATE TABLE words
(
  meme_id character varying,
  occurances double precision,
  id character varying
)
```
