### ISSUE TITLE
lots of 500 errors

### ISSUE THREAD

**Issue by ajloveslily14** [jacebrowning/memegen#449]
a good chunk of the API isn't working, for instance https://memegen.link/api/templates/sad-biden

https://memegen.link/api/

**Comment by jacebrowning** [comment]
Thanks for the report!

This is the error:

```
2018-11-08T13:55:35.515851+00:00 app[web.1]: [2018-11-08 13:55:35,515] ERROR in app: Exception on /api/ [GET]
2018-11-08T13:55:35.515861+00:00 app[web.1]: Traceback (most recent call last):
2018-11-08T13:55:35.515866+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
2018-11-08T13:55:35.515867+00:00 app[web.1]: response = self.full_dispatch_request()
2018-11-08T13:55:35.515869+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1615, in full_dispatch_request
2018-11-08T13:55:35.515870+00:00 app[web.1]: return self.finalize_request(rv)
2018-11-08T13:55:35.515884+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1630, in finalize_request
2018-11-08T13:55:35.515886+00:00 app[web.1]: response = self.make_response(rv)
2018-11-08T13:55:35.515887+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask_api/app.py", line 60, in make_response
2018-11-08T13:55:35.515889+00:00 app[web.1]: rv = self.response_class(rv, headers=headers, status=status)
2018-11-08T13:55:35.515891+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask_api/response.py", line 20, in __init__
2018-11-08T13:55:35.515893+00:00 app[web.1]: content = renderer.render(content, media_type, **options)
2018-11-08T13:55:35.515894+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask_api/renderers.py", line 103, in render
2018-11-08T13:55:35.515896+00:00 app[web.1]: view_description = apply_markdown(view_description)
2018-11-08T13:55:35.515898+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask_api/compat.py", line 16, in apply_markdown
2018-11-08T13:55:35.515900+00:00 app[web.1]: md = markdown.Markdown(extensions=extensions)
2018-11-08T13:55:35.515901+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/markdown/core.py", line 100, in __init__
2018-11-08T13:55:35.515903+00:00 app[web.1]: configs=kwargs.get('extension_configs', {}))
2018-11-08T13:55:35.515905+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/markdown/core.py", line 126, in registerExtensions
2018-11-08T13:55:35.515906+00:00 app[web.1]: ext = self.build_extension(ext, configs.get(ext, {}))
2018-11-08T13:55:35.515908+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/markdown/core.py", line 166, in build_extension
2018-11-08T13:55:35.515910+00:00 app[web.1]: module = importlib.import_module(ext_name)
2018-11-08T13:55:35.515911+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/importlib/__init__.py", line 126, in import_module
2018-11-08T13:55:35.515913+00:00 app[web.1]: return _bootstrap._gcd_import(name[level:], package, level)
2018-11-08T13:55:35.515914+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 994, in _gcd_import
2018-11-08T13:55:35.515916+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 971, in _find_and_load
2018-11-08T13:55:35.515917+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
2018-11-08T13:55:35.515924+00:00 app[web.1]: ModuleNotFoundError: No module named 'headerid(level=2)'
```

I'm not sure what has changed here, but I'm investigating.

I've also updated my monitoring service to check the API.

**Comment by jacebrowning** [comment]
This was broken in https://github.com/jacebrowning/memegen/pull/445
