### ISSUE TITLE
No module named 'log'

### ISSUE THREAD

**Issue by mbuechner** [jacebrowning/memegen#455]
I am getting:
```
Traceback (most recent call last):
  File "manage.py", line 6, in <module>
    from memegen.factory import create_app
  File "/home/memegen/memegen/factory.py", line 8, in <module>
    import log
ModuleNotFoundError: No module named 'log'
```
Guess there's a module missing. Which one is it?

**Comment by jacebrowning** [comment]
The dependency is defined here: https://github.com/jacebrowning/memegen/blob/f6be3f6a0532d4a030fc7f78503970f490a25e8e/Pipfile#L24

Which command did you run that produced this failure?

**Comment by mbuechner** [comment]
`pipenv install --system --deploy` did the trick! (My fault! I did not understand the idea of `pipenv`.)

I dockerized memegen. May helpful for someone else!?
```
FROM python:3.6-alpine
RUN apk add --no-cache --virtual .build-deps git gcc make build-base bash jpeg-dev zlib-dev tiff-dev freetype-dev lcms2-dev tk-dev tcl-dev openjpeg-dev
RUN git clone https://github.com/jacebrowning/memegen.git /home/memegen
RUN pip install pipenv
WORKDIR /home/memegen
RUN pipenv install --system --deploy --ignore-pipfile

ENTRYPOINT ["python", "manage.py", "runserver", "--host", "0.0.0.0", "--port", "5000"]

EXPOSE 5000
```
