### ISSUE TITLE
Last webp or asdf update broke memegen in Container

### ISSUE THREAD

**Issue by Helvio88** [jacebrowning/memegen#787]
Compilation works from `Containerfile` but this is the log output:

```[2023-02-23 20:58:43 +0000] [7] [INFO] Starting gunicorn 20.1.0
[2023-02-23 20:58:43 +0000] [7] [INFO] Listening at: http://0.0.0.0:5000 (7)
[2023-02-23 20:58:43 +0000] [7] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2023-02-23 20:58:43 +0000] [8] [INFO] Booting worker with pid: 8
[2023-02-23 20:58:44 +0000] [8] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/opt/memegen/.local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/opt/memegen/.local/lib/python3.11/site-packages/uvicorn/workers.py", line 66, in init_process
    super(UvicornWorker, self).init_process()
  File "/opt/memegen/.local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/opt/memegen/.local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/opt/memegen/.local/lib/python3.11/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/opt/memegen/.local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/memegen/.local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/memegen/.local/lib/python3.11/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/memegen/app/main.py", line 7, in <module>
    from app import config, helpers, settings, utils
  File "/opt/memegen/app/config.py", line 10, in <module>
    from . import settings, utils, views
  File "/opt/memegen/app/utils/__init__.py", line 1, in <module>
    from . import html, http, images, meta, text, urls
  File "/opt/memegen/app/utils/images.py", line 7, in <module>
    import webp
  File "/opt/memegen/.local/lib/python3.11/site-packages/webp/__init__.py", line 6, in <module>
    from _webp import ffi, lib
ModuleNotFoundError: No module named '_webp'
[2023-02-23 20:58:44 +0000] [8] [INFO] Worker exiting (pid: 8)
[2023-02-23 20:58:44 +0000] [7] [INFO] Shutting down: Master
[2023-02-23 20:58:44 +0000] [7] [INFO] Reason: Worker failed to boot.
[2023-02-23 20:58:45 +0000] [8] [INFO] Starting gunicorn 20.1.0
[2023-02-23 20:58:45 +0000] [8] [INFO] Listening at: http://0.0.0.0:5000 (8)
[2023-02-23 20:58:45 +0000] [8] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2023-02-23 20:58:45 +0000] [9] [INFO] Booting worker with pid: 9
[2023-02-23 20:58:45 +0000] [9] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/opt/memegen/.local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/opt/memegen/.local/lib/python3.11/site-packages/uvicorn/workers.py", line 66, in init_process
    super(UvicornWorker, self).init_process()
  File "/opt/memegen/.local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/opt/memegen/.local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/opt/memegen/.local/lib/python3.11/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/opt/memegen/.local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/memegen/.local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/memegen/.local/lib/python3.11/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/memegen/app/main.py", line 7, in <module>
    from app import config, helpers, settings, utils
  File "/opt/memegen/app/config.py", line 10, in <module>
    from . import settings, utils, views
  File "/opt/memegen/app/utils/__init__.py", line 1, in <module>
    from . import html, http, images, meta, text, urls
  File "/opt/memegen/app/utils/images.py", line 7, in <module>
    import webp
  File "/opt/memegen/.local/lib/python3.11/site-packages/webp/__init__.py", line 6, in <module>
    from _webp import ffi, lib
ModuleNotFoundError: No module named '_webp'
[2023-02-23 20:58:45 +0000] [9] [INFO] Worker exiting (pid: 9)
[2023-02-23 20:58:46 +0000] [8] [INFO] Shutting down: Master
[2023-02-23 20:58:46 +0000] [8] [INFO] Reason: Worker failed to boot.
[2023-02-23 20:58:47 +0000] [8] [INFO] Starting gunicorn 20.1.0
[2023-02-23 20:58:47 +0000] [8] [INFO] Listening at: http://0.0.0.0:5000 (8)
[2023-02-23 20:58:47 +0000] [8] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2023-02-23 20:58:47 +0000] [9] [INFO] Booting worker with pid: 9
[2023-02-23 20:58:47 +0000] [9] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/opt/memegen/.local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/opt/memegen/.local/lib/python3.11/site-packages/uvicorn/workers.py", line 66, in init_process
    super(UvicornWorker, self).init_process()
  File "/opt/memegen/.local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/opt/memegen/.local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/opt/memegen/.local/lib/python3.11/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/opt/memegen/.local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/memegen/.local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/memegen/.local/lib/python3.11/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/memegen/app/main.py", line 7, in <module>
    from app import config, helpers, settings, utils
  File "/opt/memegen/app/config.py", line 10, in <module>
    from . import settings, utils, views
  File "/opt/memegen/app/utils/__init__.py", line 1, in <module>
    from . import html, http, images, meta, text, urls
  File "/opt/memegen/app/utils/images.py", line 7, in <module>
    import webp
  File "/opt/memegen/.local/lib/python3.11/site-packages/webp/__init__.py", line 6, in <module>
    from _webp import ffi, lib
ModuleNotFoundError: No module named '_webp'
[2023-02-23 20:58:47 +0000] [9] [INFO] Worker exiting (pid: 9)
[2023-02-23 20:58:47 +0000] [8] [INFO] Shutting down: Master
[2023-02-23 20:58:47 +0000] [8] [INFO] Reason: Worker failed to boot.
[2023-02-23 20:58:49 +0000] [9] [INFO] Starting gunicorn 20.1.0
[2023-02-23 20:58:49 +0000] [9] [INFO] Listening at: http://0.0.0.0:5000 (9)
[2023-02-23 20:58:49 +0000] [9] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2023-02-23 20:58:49 +0000] [10] [INFO] Booting worker with pid: 10
[2023-02-23 20:58:49 +0000] [10] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/opt/memegen/.local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/opt/memegen/.local/lib/python3.11/site-packages/uvicorn/workers.py", line 66, in init_process
    super(UvicornWorker, self).init_process()
  File "/opt/memegen/.local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/opt/memegen/.local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/opt/memegen/.local/lib/python3.11/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/opt/memegen/.local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/memegen/.local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/memegen/.local/lib/python3.11/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/memegen/app/main.py", line 7, in <module>
    from app import config, helpers, settings, utils
  File "/opt/memegen/app/config.py", line 10, in <module>
    from . import settings, utils, views
  File "/opt/memegen/app/utils/__init__.py", line 1, in <module>
    from . import html, http, images, meta, text, urls
  File "/opt/memegen/app/utils/images.py", line 7, in <module>
    import webp
  File "/opt/memegen/.local/lib/python3.11/site-packages/webp/__init__.py", line 6, in <module>
    from _webp import ffi, lib
ModuleNotFoundError: No module named '_webp'
[2023-02-23 20:58:49 +0000] [10] [INFO] Worker exiting (pid: 10)
[2023-02-23 20:58:49 +0000] [9] [INFO] Shutting down: Master
[2023-02-23 20:58:49 +0000] [9] [INFO] Reason: Worker failed to boot.
[2023-02-23 20:58:51 +0000] [8] [INFO] Starting gunicorn 20.1.0
[2023-02-23 20:58:51 +0000] [8] [INFO] Listening at: http://0.0.0.0:5000 (8)
[2023-02-23 20:58:51 +0000] [8] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2023-02-23 20:58:51 +0000] [9] [INFO] Booting worker with pid: 9
[2023-02-23 20:58:51 +0000] [9] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/opt/memegen/.local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/opt/memegen/.local/lib/python3.11/site-packages/uvicorn/workers.py", line 66, in init_process
    super(UvicornWorker, self).init_process()
  File "/opt/memegen/.local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/opt/memegen/.local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/opt/memegen/.local/lib/python3.11/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/opt/memegen/.local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/memegen/.local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/memegen/.local/lib/python3.11/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/memegen/app/main.py", line 7, in <module>
    from app import config, helpers, settings, utils
  File "/opt/memegen/app/config.py", line 10, in <module>
    from . import settings, utils, views
  File "/opt/memegen/app/utils/__init__.py", line 1, in <module>
    from . import html, http, images, meta, text, urls
  File "/opt/memegen/app/utils/images.py", line 7, in <module>
    import webp
  File "/opt/memegen/.local/lib/python3.11/site-packages/webp/__init__.py", line 6, in <module>
    from _webp import ffi, lib
ModuleNotFoundError: No module named '_webp'
[2023-02-23 20:58:51 +0000] [9] [INFO] Worker exiting (pid: 9)
[2023-02-23 20:58:51 +0000] [8] [INFO] Shutting down: Master
[2023-02-23 20:58:51 +0000] [8] [INFO] Reason: Worker failed to boot.
[2023-02-23 20:58:54 +0000] [8] [INFO] Starting gunicorn 20.1.0
[2023-02-23 20:58:54 +0000] [8] [INFO] Listening at: http://0.0.0.0:5000 (8)
[2023-02-23 20:58:54 +0000] [8] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2023-02-23 20:58:54 +0000] [9] [INFO] Booting worker with pid: 9
[2023-02-23 20:58:54 +0000] [9] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/opt/memegen/.local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/opt/memegen/.local/lib/python3.11/site-packages/uvicorn/workers.py", line 66, in init_process
    super(UvicornWorker, self).init_process()
  File "/opt/memegen/.local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/opt/memegen/.local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/opt/memegen/.local/lib/python3.11/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/opt/memegen/.local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/memegen/.local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/memegen/.local/lib/python3.11/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/memegen/app/main.py", line 7, in <module>
    from app import config, helpers, settings, utils
  File "/opt/memegen/app/config.py", line 10, in <module>
    from . import settings, utils, views
  File "/opt/memegen/app/utils/__init__.py", line 1, in <module>
    from . import html, http, images, meta, text, urls
  File "/opt/memegen/app/utils/images.py", line 7, in <module>
    import webp
  File "/opt/memegen/.local/lib/python3.11/site-packages/webp/__init__.py", line 6, in <module>
    from _webp import ffi, lib
ModuleNotFoundError: No module named '_webp'
[2023-02-23 20:58:54 +0000] [9] [INFO] Worker exiting (pid: 9)
[2023-02-23 20:58:54 +0000] [8] [INFO] Shutting down: Master
[2023-02-23 20:58:54 +0000] [8] [INFO] Reason: Worker failed to boot.
[2023-02-23 20:58:59 +0000] [8] [INFO] Starting gunicorn 20.1.0
[2023-02-23 20:58:59 +0000] [8] [INFO] Listening at: http://0.0.0.0:5000 (8)
[2023-02-23 20:58:59 +0000] [8] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2023-02-23 20:58:59 +0000] [9] [INFO] Booting worker with pid: 9
[2023-02-23 20:58:59 +0000] [9] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/opt/memegen/.local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/opt/memegen/.local/lib/python3.11/site-packages/uvicorn/workers.py", line 66, in init_process
    super(UvicornWorker, self).init_process()
  File "/opt/memegen/.local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/opt/memegen/.local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/opt/memegen/.local/lib/python3.11/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/opt/memegen/.local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/memegen/.local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/memegen/.local/lib/python3.11/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/memegen/app/main.py", line 7, in <module>
    from app import config, helpers, settings, utils
  File "/opt/memegen/app/config.py", line 10, in <module>
    from . import settings, utils, views
  File "/opt/memegen/app/utils/__init__.py", line 1, in <module>
    from . import html, http, images, meta, text, urls
  File "/opt/memegen/app/utils/images.py", line 7, in <module>
    import webp
  File "/opt/memegen/.local/lib/python3.11/site-packages/webp/__init__.py", line 6, in <module>
    from _webp import ffi, lib
ModuleNotFoundError: No module named '_webp'
[2023-02-23 20:58:59 +0000] [9] [INFO] Worker exiting (pid: 9)
[2023-02-23 20:58:59 +0000] [8] [INFO] Shutting down: Master
[2023-02-23 20:58:59 +0000] [8] [INFO] Reason: Worker failed to boot.
[2023-02-23 20:59:06 +0000] [8] [INFO] Starting gunicorn 20.1.0
[2023-02-23 20:59:06 +0000] [8] [INFO] Listening at: http://0.0.0.0:5000 (8)
[2023-02-23 20:59:06 +0000] [8] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2023-02-23 20:59:06 +0000] [9] [INFO] Booting worker with pid: 9
[2023-02-23 20:59:07 +0000] [9] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/opt/memegen/.local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/opt/memegen/.local/lib/python3.11/site-packages/uvicorn/workers.py", line 66, in init_process
    super(UvicornWorker, self).init_process()
  File "/opt/memegen/.local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/opt/memegen/.local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/opt/memegen/.local/lib/python3.11/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/opt/memegen/.local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/memegen/.local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/memegen/.local/lib/python3.11/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/memegen/app/main.py", line 7, in <module>
    from app import config, helpers, settings, utils
  File "/opt/memegen/app/config.py", line 10, in <module>
    from . import settings, utils, views
  File "/opt/memegen/app/utils/__init__.py", line 1, in <module>
    from . import html, http, images, meta, text, urls
  File "/opt/memegen/app/utils/images.py", line 7, in <module>
    import webp
  File "/opt/memegen/.local/lib/python3.11/site-packages/webp/__init__.py", line 6, in <module>
    from _webp import ffi, lib
ModuleNotFoundError: No module named '_webp'
[2023-02-23 20:59:07 +0000] [9] [INFO] Worker exiting (pid: 9)
[2023-02-23 20:59:07 +0000] [8] [INFO] Shutting down: Master
[2023-02-23 20:59:07 +0000] [8] [INFO] Reason: Worker failed to boot.
[2023-02-23 20:59:21 +0000] [7] [INFO] Starting gunicorn 20.1.0
[2023-02-23 20:59:21 +0000] [7] [INFO] Listening at: http://0.0.0.0:5000 (7)
[2023-02-23 20:59:21 +0000] [7] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2023-02-23 20:59:21 +0000] [8] [INFO] Booting worker with pid: 8
[2023-02-23 20:59:21 +0000] [8] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/opt/memegen/.local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/opt/memegen/.local/lib/python3.11/site-packages/uvicorn/workers.py", line 66, in init_process
    super(UvicornWorker, self).init_process()
  File "/opt/memegen/.local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/opt/memegen/.local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/opt/memegen/.local/lib/python3.11/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/opt/memegen/.local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/memegen/.local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/memegen/.local/lib/python3.11/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/memegen/app/main.py", line 7, in <module>
    from app import config, helpers, settings, utils
  File "/opt/memegen/app/config.py", line 10, in <module>
    from . import settings, utils, views
  File "/opt/memegen/app/utils/__init__.py", line 1, in <module>
    from . import html, http, images, meta, text, urls
  File "/opt/memegen/app/utils/images.py", line 7, in <module>
    import webp
  File "/opt/memegen/.local/lib/python3.11/site-packages/webp/__init__.py", line 6, in <module>
    from _webp import ffi, lib
ModuleNotFoundError: No module named '_webp'
[2023-02-23 20:59:21 +0000] [8] [INFO] Worker exiting (pid: 8)
[2023-02-23 20:59:21 +0000] [7] [INFO] Shutting down: Master
[2023-02-23 20:59:21 +0000] [7] [INFO] Reason: Worker failed to boot.```

**Comment by jacebrowning** [comment]
I updated `webp` because it was broken on CI: 

> ImportError: cannot import name 'conan_api' from 'conans.client' (/tmp/pip-build-env-6qvbiiq0/overlay/lib/python3.11/site-packages/conans/client/__init__.py)

https://app.circleci.com/pipelines/github/jacebrowning/memegen/1872/workflows/70636f32-c3b3-41dd-94cd-37383a4faf60/jobs/1852/parallel-runs/0/steps/0-104

**Comment by Helvio88** [comment]
Yupp, I have experienced that error too when building the container image. Now it builds, but doesn't start. I think it's webp related, but I can't properly debug it as I'm not experienced enough :(

**Comment by jacebrowning** [comment]
It might be worth opening an issue on https://github.com/anibali/pywebp if you can create a minimal reproducible example.
